name: Deploy to Firebase Hosting

on:
  push:
    branches: [main] # Replace 'main' with your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: firebase/action-firebase-login@v3
        with:
          creds: ${{ secrets.FIREBASE_TOKEN }}
      - run: npm install
      - run: npm run build
      - run: firebase deploy --only hosting